### ISSUE TITLE
Bug:`exit a a`などでtoo many argumentsとして判定されexitされない

### ISSUE THREAD

**Issue by Yono1112** [Yono1112/ft_minishell#48]
**Describe the bug**
- `exit a a`などでtoo many argumentsとして判定されexitされない

**To Reproduce**
- $ exit a a
- minishell: exit: too many arguments: Undefined error: 0
- $ 

**Expected behavior**
- $ exit a a
- exit \n bash: exit: a: numeric argument required

**Other additional information**
- bashではexitされる。

**Comment by Yono1112** [comment]
- 第一引数に数字である時は第二引数以降がある時`too many argument`としてエラーが出る、この時はexitされない
- ex) $ exit 42 a 41 
- bash: exit: too many arguments
- $ 

- 第一引数に数字以外がある時は第二引数以降にどんな文字がきたとしても`numeric argument required`としてexitされる
- ex) $ exit a 42
- bash: exit: a: numeric argument required
- ex) $ exit 42a 42
- bash: exit: a: numeric argument required

**Comment by rnakaa** [comment]
ok!
